config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [ :index, :show, :new, :create ] do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :phone_number, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, acceptance: { accept: ['Chinese', 'Italian', 'Japanese', 'French', 'Belgian'] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    # restaurant_params = params[:restaurant]
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    # raise
    restaurant = Restaurant.find(params[:restaurant_id])
    review = Review.new(review_params)
    # raise
    review.restaurant = restaurant
    review.save

    redirect_to restaurant_path(restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<!-- <p>hello from restaurants!! loaded via restaurants#index</p> -->

<h2>Welcome to this yelp clone</h2>
<p>Here are restaurants in this area:</p>


<% @restaurants.each do |restaurant| %>

<ul>
  <li> <%= restaurant.name %>
        <%= link_to 'more', restaurant_path(restaurant) %>
  </li>
</ul>

<% end %>

app/views/restaurants/new.html.erb
<h2>Create a new restaurant</h2>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, label: 'Restaurant name', placeholder: 'San Marzanos' %>
  <%= f.input :address, placeholder: 'address' %>
  <%= f.input :phone_number, placeholder: 'phone number' %>
  <%= f.input :category, priority: [ "" ], collection: ['Chinese', 'Italian', 'Japanese', 'French', 'Belgian'] %>
  <%= f.button :submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2> <%= @restaurant.name %> </h2>

<p> <%= @restaurant.address %> </p>
<p> <%= @restaurant.category %> </p>
<p> <%= @restaurant.phone_number %> </p>

<h4>Reviews</h4>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <p>
        <%= review.rating %> stars.
        <%= review.content %>
      </p>
    </li>
  <% end %>
</ul>


<%= link_to 'Add review', new_restaurant_review_path(@restaurant) %>

<%= link_to 'Back to home', restaurants_path %>

app/views/reviews/new.html.erb
<h2>Create a new review</h2>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, placeholder: '1 - 5 stars' %>
  <%= f.input :content, placeholder: 'Your review' %>
  <%= f.button :submit %>

<% end %>